// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chatbot/internal/conf"
	"chatbot/internal/server"
	"chatbot/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(string2 string, bootstrap_DING *conf.Bootstrap_DING, confServer *conf.Server, logger log.Logger) (*kratos.App, func(), error) {
	userServiceInterface := service.NewUserService()
	greeterService := service.NewGreeterService(string2, bootstrap_DING, userServiceInterface)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
